version: 1.0.{build}
image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
install:
  - cmd: git submodule update --init --recursive
build_script:
  - cmd: >-
      cd C:\projects\influxdblptool
      mkdir build
      cd build
      cmake .. -Dgtest_force_shared_crt=ON -DCMAKE_BUILD_TYPE=Release
      msbuild influxdblptool.sln /p:Configuration=Release
test_script:
  - cmd: msbuild RUN_TESTS.vcxproj /p:Configuration=Release
notifications:
  - provider: Email
    to:
      - patrick@crosscode.nl
    subject: AppVeyor build influxdblptool
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
branches:
  only:
    - master
    - develop